# Generated by Django 5.1.6 on 2025-11-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='joined',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
