# Generated by Django 5.1.6 on 2025-11-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0002_alter_useraccount_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
