# Generated by Django 5.1.6 on 2025-11-24 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0003_useraccount_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='is_featured',
        ),
    ]
