# Generated by Django 5.1.6 on 2025-12-16 16:18

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0004_remove_useraccount_is_featured'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('hero_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('section_features', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('awards', models.CharField(max_length=200)),
                ('agents', models.CharField(max_length=200)),
                ('visites', models.CharField(max_length=200)),
                ('place_image_1', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('place_title_1', models.CharField(max_length=200)),
                ('place_image_2', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('place_title_2', models.CharField(max_length=200)),
                ('place_image_3', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('place_title_3', models.CharField(max_length=200)),
                ('place_image_4', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('place_title_4', models.CharField(max_length=200)),
                ('place_image_5', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('place_title_5', models.CharField(max_length=200)),
                ('place_image_6', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
                ('place_title_6', models.CharField(max_length=200)),
                ('section_steps', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='test',
            name='agent',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='listing_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
