# Generated by Django 5.1.6 on 2025-12-17 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0006_alter_home_page_agents_alter_home_page_awards_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='test',
            name='phone_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
