# Generated by Django 5.1.6 on 2025-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0007_alter_test_date_alter_test_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='responsable',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
