# Generated by Django 5.1.6 on 2025-12-18 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0009_alter_awards_image_alter_home_page_hero_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_visible',
            field=models.BooleanField(default=True),
        ),
    ]
