# Generated by Django 5.1.6 on 2025-12-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0010_alter_product_is_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
