# Generated by Django 5.1.6 on 2025-11-13 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0056_rename_name_awards_badrbadroomes_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image_ar',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='licence',
        ),
        migrations.RemoveField(
            model_name='post',
            name='time',
        ),
    ]
