# Generated by Django 5.1.6 on 2025-11-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0058_remove_post_url_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
