# Generated by Django 5.1.6 on 2025-11-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0059_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_owner',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
