# Generated by Django 5.1.6 on 2025-11-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0061_rename_title_test_date_remove_test_image_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
