# Generated by Django 5.1.6 on 2025-11-17 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0062_order_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
