# Generated by Django 5.1.6 on 2025-11-18 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0063_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amenities',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Amenities', to='padlevap.product'),
        ),
    ]
