# Generated by Django 5.1.6 on 2025-11-18 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0064_alter_amenities_product'),
    ]

    operations = [
    ]
