# Generated by Django 5.1.6 on 2025-11-19 09:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('padlevap', '0065_auto_20251118_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='images'),
        ),
    ]
